version: '3.9'
services:
  game-server:
    container_name: game-one-server
    hostname: game-one-server
    build:
      context: .
      dockerfile: docker/Dockerfile-server
    restart: always
    environment:
      PORT: "3000"
      VERSION: "1.0.0"
    ports:
      - "3000:3000"

